version: "3"

services:    
    influxdb:
        env_file:
            - .env
        image: influxdb:1.8
        container_name: potpourri-persistence-influxdb
        volumes:
            - influxdb:/var/lib/influxdb
        networks:
            - default
        ports:
            - ${influxdb_port}:8086
        restart: always

    telegraf:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.telegraf
        container_name: potpourri-persistence-telegraf
        networks:
            - default
            - potpourri-mqtt-broker_default
        depends_on:
            - influxdb
        restart: always

volumes:
    influxdb:

networks:
    default:
        driver: bridge
    potpourri-mqtt-broker_default:
        external: true
