version: "3"

services:
  datastore:
    build: datastore
    volumes:
      - ./datastore/db:/app/db
    ports:
      - 3000:3000
    restart: always

  ui:
    build: ui
    ports:
      - 3002:3002
    depends_on:
      - datastore
    restart: always
    environment:
      - DATASTORE_HOSTNAME=${hostname}
      - DATASTORE_PORT=3000
