version: "3"

services:    
    datastore:
        env_file:
            - .env
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: potpourri-datastore
        volumes:
          - ./datastore/db:/app/db
        ports:
            - ${datastore_port}:3000
        restart: always

