# choose the base image to build upon
FROM node:10.9-alpine

# define working directory
WORKDIR /app

# copy files needed for installation...
COPY package*.json ./
COPY ./package.json package

# ... then install dependencies
RUN npm install

# add application code
COPY . .
