version: "3"

services:    
    ui:
        env_file:
            - .env
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: potpourri-ui
        ports:
            - ${ui_port}:3002
        restart: always
        environment:
            - DATASTORE_HOSTNAME=${hostname}
            - DATASTORE_PORT=${datastore_port}

