version: "3"

services:
  datastore:
    env_file:
      - .env
    build: datastore
    volumes:
      - ./datastore/db:/app/db
    ports:
      - ${datastore_port}:3000
    restart: always

  ui:
    env_file:
      - .env
    build: ui
    ports:
      - ${ui_port}:3002
    depends_on:
      - datastore
    restart: always
    environment:
      - DATASTORE_HOSTNAME=${hostname}
      - DATASTORE_PORT=${datastore_port}
