version: "3"

services:    
    webapp:
        env_file:
            - .env
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: potpourri-webapp
        ports:
            - ${webapp_port}:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always

