version: "3"

services:
    mqtt-broker:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.aarch64
        container_name: potpourri-mqtt-broker
        ports:
            - ${mqtt_broker_port}:1883
        restart: always
