version: "3"

services:
    grafana:
        env_file:
            - .env
        image: grafana/grafana
        container_name: potpourri-visualization-grafana
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./grafana/provisioning:/etc/grafana/provisioning:ro
        ports:
            - ${grafana_port}:3000
        restart: always

volumes:
    grafana:
