@startuml Wifi Device Flowchart
skinparam componentStyle uml2

participant "MQTT Broker"
participant "Device"
participant "Sensors"
participant "Actuators"

Device -> Device: wake-up\nevent
Activate Device

== Read Sensors ==

Device -> Sensors: power-on\nSensors
Activate Sensors
Sensors -> Device: provide\ndata
Device -> Device: read data
Device -> Sensors: power-off\nSensors
Deactivate Sensors

Device -> Device: prepare data

== Send Data to MQTT Broker ==

Device -> "MQTT Broker": send data

Activate "MQTT Broker"
"MQTT Broker" -> Device: send\nacknowledge-\nment
Deactivate "MQTT Broker"

== Fetch accumulated events ==

Device -> "MQTT Broker": check for events
Activate "MQTT Broker"
"MQTT Broker" -> Device: send events
Deactivate "MQTT Broker"

== Control Actuators ==

opt in case of events received
    
    Device -> Actuators: control
    Activate Actuators
    Deactivate Actuators

end

Device -> Device: go to\ndeep sleep
Deactivate Device

@enduml