version: "3"

services:
    mongodb:
        env_file:
            - .env
        image: mongo:4.2-bionic
        container_name: potpourri-metastore-mongodb
        volumes:
            - mongodb:/data/db
        ports:
            - ${MONGODB_PORT}:27017
        restart: always

    metastore:
        env_file:
            - .env
        build:
            context: .
        container_name: potpourri-metastore
        volumes:
            - store:/usr/src/app/store
        ports:
            - ${METASTORE_PORT}:3003
        depends_on:
            - mongodb
        restart: always

volumes:
    store:
    mongodb:
